// This file is generated by kconfig_compiler from smartpinyin.kcfg.
// All changes you do to this file will be lost.

#include "smartpinyin.h"

#include <kstaticdeleter.h>

SmartPinyinConfig *SmartPinyinConfig::mSelf = 0;
static KStaticDeleter<SmartPinyinConfig> staticSmartPinyinConfigDeleter;

SmartPinyinConfig *SmartPinyinConfig::self()
{
  if ( !mSelf ) {
    staticSmartPinyinConfigDeleter.setObject( mSelf, new SmartPinyinConfig() );
    mSelf->readConfig();
  }

  return mSelf;
}

SmartPinyinConfig::SmartPinyinConfig(  )
  : KConfigSkeleton( QString::fromLatin1( "skimrc" ) )
{
  mSelf = this;
  setCurrentGroup( QString::fromLatin1( "SCIM" ) );

  KConfigSkeleton::ItemBool  *item_IMEngine_Pinyin_AlwaysShowLookup;
  item_IMEngine_Pinyin_AlwaysShowLookup = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/AlwaysShowLookup" ), m_IMEngine_Pinyin_AlwaysShowLookup, false );
  addItem( item_IMEngine_Pinyin_AlwaysShowLookup, QString::fromLatin1( "_IMEngine_Pinyin_AlwaysShowLookup" ) );
  KConfigSkeleton::ItemBool  *item_IMEngine_Pinyin_Ambiguities;
  item_IMEngine_Pinyin_Ambiguities = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/Ambiguity/Any" ), m_IMEngine_Pinyin_Ambiguities, false );
  addItem( item_IMEngine_Pinyin_Ambiguities, QString::fromLatin1( "_IMEngine_Pinyin_Ambiguities" ) );
  KConfigSkeleton::ItemBool  *item_IMEngine_Pinyin_Ambiguity_AnAng;
  item_IMEngine_Pinyin_Ambiguity_AnAng = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/Ambiguity/AnAng" ), m_IMEngine_Pinyin_Ambiguity_AnAng, false );
  addItem( item_IMEngine_Pinyin_Ambiguity_AnAng, QString::fromLatin1( "_IMEngine_Pinyin_Ambiguity_AnAng" ) );
  KConfigSkeleton::ItemBool  *item_IMEngine_Pinyin_Ambiguity_EnEng;
  item_IMEngine_Pinyin_Ambiguity_EnEng = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/Ambiguity/EnEng" ), m_IMEngine_Pinyin_Ambiguity_EnEng, false );
  addItem( item_IMEngine_Pinyin_Ambiguity_EnEng, QString::fromLatin1( "_IMEngine_Pinyin_Ambiguity_EnEng" ) );
  KConfigSkeleton::ItemBool  *item_IMEngine_Pinyin_Ambiguity_InIng;
  item_IMEngine_Pinyin_Ambiguity_InIng = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/Ambiguity/InIng" ), m_IMEngine_Pinyin_Ambiguity_InIng, false );
  addItem( item_IMEngine_Pinyin_Ambiguity_InIng, QString::fromLatin1( "_IMEngine_Pinyin_Ambiguity_InIng" ) );
  KConfigSkeleton::ItemBool  *item_IMEngine_Pinyin_Ambiguity_ZhiZi;
  item_IMEngine_Pinyin_Ambiguity_ZhiZi = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/Ambiguity/ZhiZi" ), m_IMEngine_Pinyin_Ambiguity_ZhiZi, false );
  addItem( item_IMEngine_Pinyin_Ambiguity_ZhiZi, QString::fromLatin1( "_IMEngine_Pinyin_Ambiguity_ZhiZi" ) );
  KConfigSkeleton::ItemBool  *item_IMEngine_Pinyin_Ambiguity_ChiCi;
  item_IMEngine_Pinyin_Ambiguity_ChiCi = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/Ambiguity/ChiCi" ), m_IMEngine_Pinyin_Ambiguity_ChiCi, false );
  addItem( item_IMEngine_Pinyin_Ambiguity_ChiCi, QString::fromLatin1( "_IMEngine_Pinyin_Ambiguity_ChiCi" ) );
  KConfigSkeleton::ItemBool  *item_IMEngine_Pinyin_Ambiguity_ShiSi;
  item_IMEngine_Pinyin_Ambiguity_ShiSi = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/Ambiguity/ShiSi" ), m_IMEngine_Pinyin_Ambiguity_ShiSi, false );
  addItem( item_IMEngine_Pinyin_Ambiguity_ShiSi, QString::fromLatin1( "_IMEngine_Pinyin_Ambiguity_ShiSi" ) );
  KConfigSkeleton::ItemBool  *item_IMEngine_Pinyin_Ambiguity_FoHe;
  item_IMEngine_Pinyin_Ambiguity_FoHe = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/Ambiguity/FoHe" ), m_IMEngine_Pinyin_Ambiguity_FoHe, false );
  addItem( item_IMEngine_Pinyin_Ambiguity_FoHe, QString::fromLatin1( "_IMEngine_Pinyin_Ambiguity_FoHe" ) );
  KConfigSkeleton::ItemBool  *item_IMEngine_Pinyin_Ambiguity_LeRi;
  item_IMEngine_Pinyin_Ambiguity_LeRi = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/Ambiguity/LeRi" ), m_IMEngine_Pinyin_Ambiguity_LeRi, false );
  addItem( item_IMEngine_Pinyin_Ambiguity_LeRi, QString::fromLatin1( "_IMEngine_Pinyin_Ambiguity_LeRi" ) );
  KConfigSkeleton::ItemBool  *item_IMEngine_Pinyin_Ambiguity_NeLe;
  item_IMEngine_Pinyin_Ambiguity_NeLe = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/Ambiguity/NeLe" ), m_IMEngine_Pinyin_Ambiguity_NeLe, false );
  addItem( item_IMEngine_Pinyin_Ambiguity_NeLe, QString::fromLatin1( "_IMEngine_Pinyin_Ambiguity_NeLe" ) );
  KConfigSkeleton::ItemBool  *item_IMEngine_Pinyin_Ambiguity_Any;
  item_IMEngine_Pinyin_Ambiguity_Any = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/Ambiguity/Any" ), m_IMEngine_Pinyin_Ambiguity_Any, false );
  addItem( item_IMEngine_Pinyin_Ambiguity_Any, QString::fromLatin1( "_IMEngine_Pinyin_Ambiguity_Any" ) );
  KConfigSkeleton::ItemBool  *item_IMEngine_Pinyin_AutoCombinePhrase;
  item_IMEngine_Pinyin_AutoCombinePhrase = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/AutoCombinePhrase" ), m_IMEngine_Pinyin_AutoCombinePhrase, false );
  addItem( item_IMEngine_Pinyin_AutoCombinePhrase, QString::fromLatin1( "_IMEngine_Pinyin_AutoCombinePhrase" ) );
  KConfigSkeleton::ItemBool  *item_IMEngine_Pinyin_AutoFillPreedit;
  item_IMEngine_Pinyin_AutoFillPreedit = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/AutoFillPreedit" ), m_IMEngine_Pinyin_AutoFillPreedit, false );
  addItem( item_IMEngine_Pinyin_AutoFillPreedit, QString::fromLatin1( "_IMEngine_Pinyin_AutoFillPreedit" ) );
  KConfigSkeleton::ItemInt  *item_IMEngine_Pinyin_BurstStackSize;
  item_IMEngine_Pinyin_BurstStackSize = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/BurstStackSize" ), m_IMEngine_Pinyin_BurstStackSize, 128 );
  addItem( item_IMEngine_Pinyin_BurstStackSize, QString::fromLatin1( "_IMEngine_Pinyin_BurstStackSize" ) );
  KConfigSkeleton::ItemString  *item_IMEngine_Pinyin_ChineseSwitchKey;
  item_IMEngine_Pinyin_ChineseSwitchKey = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/ChineseSwitchKey" ), m_IMEngine_Pinyin_ChineseSwitchKey, QString::fromLatin1( "Control+slash" ) );
  addItem( item_IMEngine_Pinyin_ChineseSwitchKey, QString::fromLatin1( "_IMEngine_Pinyin_ChineseSwitchKey" ) );
  KConfigSkeleton::ItemString  *item_IMEngine_Pinyin_DisablePhraseKey;
  item_IMEngine_Pinyin_DisablePhraseKey = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/DisablePhraseKey" ), m_IMEngine_Pinyin_DisablePhraseKey, QString::fromLatin1( "Control+d" ) );
  addItem( item_IMEngine_Pinyin_DisablePhraseKey, QString::fromLatin1( "_IMEngine_Pinyin_DisablePhraseKey" ) );
  KConfigSkeleton::ItemBool  *item_IMEngine_Pinyin_DynamicAdjust;
  item_IMEngine_Pinyin_DynamicAdjust = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/DynamicAdjust" ), m_IMEngine_Pinyin_DynamicAdjust, false );
  addItem( item_IMEngine_Pinyin_DynamicAdjust, QString::fromLatin1( "_IMEngine_Pinyin_DynamicAdjust" ) );
  KConfigSkeleton::ItemInt  *item_IMEngine_Pinyin_DynamicSensitivity;
  item_IMEngine_Pinyin_DynamicSensitivity = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/DynamicSensitivity" ), m_IMEngine_Pinyin_DynamicSensitivity, 6 );
  addItem( item_IMEngine_Pinyin_DynamicSensitivity, QString::fromLatin1( "_IMEngine_Pinyin_DynamicSensitivity" ) );
  KConfigSkeleton::ItemString  *item_IMEngine_Pinyin_FullWidthLetterKey;
  item_IMEngine_Pinyin_FullWidthLetterKey = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/FullWidthLetterKey" ), m_IMEngine_Pinyin_FullWidthLetterKey, QString::fromLatin1( "Shift+space" ) );
  addItem( item_IMEngine_Pinyin_FullWidthLetterKey, QString::fromLatin1( "_IMEngine_Pinyin_FullWidthLetterKey" ) );
  KConfigSkeleton::ItemString  *item_IMEngine_Pinyin_FullWidthPunctKey;
  item_IMEngine_Pinyin_FullWidthPunctKey = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/FullWidthPunctKey" ), m_IMEngine_Pinyin_FullWidthPunctKey, QString::fromLatin1( "Control+period" ) );
  addItem( item_IMEngine_Pinyin_FullWidthPunctKey, QString::fromLatin1( "_IMEngine_Pinyin_FullWidthPunctKey" ) );
  KConfigSkeleton::ItemBool  *item_IMEngine_Pinyin_Incomplete;
  item_IMEngine_Pinyin_Incomplete = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/Incomplete" ), m_IMEngine_Pinyin_Incomplete, false );
  addItem( item_IMEngine_Pinyin_Incomplete, QString::fromLatin1( "_IMEngine_Pinyin_Incomplete" ) );
  KConfigSkeleton::ItemBool  *item_IMEngine_Pinyin_MatchLongerPhrase;
  item_IMEngine_Pinyin_MatchLongerPhrase = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/MatchLongerPhrase" ), m_IMEngine_Pinyin_MatchLongerPhrase, false );
  addItem( item_IMEngine_Pinyin_MatchLongerPhrase, QString::fromLatin1( "_IMEngine_Pinyin_MatchLongerPhrase" ) );
  KConfigSkeleton::ItemInt  *item_IMEngine_Pinyin_MaxPreeditLength;
  item_IMEngine_Pinyin_MaxPreeditLength = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/MaxPreeditLength" ), m_IMEngine_Pinyin_MaxPreeditLength, 32 );
  addItem( item_IMEngine_Pinyin_MaxPreeditLength, QString::fromLatin1( "_IMEngine_Pinyin_MaxPreeditLength" ) );
  KConfigSkeleton::ItemInt  *item_IMEngine_Pinyin_MaxUserPhraseLength;
  item_IMEngine_Pinyin_MaxUserPhraseLength = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/MaxUserPhraseLength" ), m_IMEngine_Pinyin_MaxUserPhraseLength, 8 );
  addItem( item_IMEngine_Pinyin_MaxUserPhraseLength, QString::fromLatin1( "_IMEngine_Pinyin_MaxUserPhraseLength" ) );
  KConfigSkeleton::ItemString  *item_IMEngine_Pinyin_ModeSwitchKey;
  item_IMEngine_Pinyin_ModeSwitchKey = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/ModeSwitchKey" ), m_IMEngine_Pinyin_ModeSwitchKey, QString::fromLatin1( "Alt+Shift_L+KeyRelease,Alt+Shift_R+KeyRelease,Shift+Shift_L+KeyRelease,Shift+Shift_R+KeyRelease" ) );
  addItem( item_IMEngine_Pinyin_ModeSwitchKey, QString::fromLatin1( "_IMEngine_Pinyin_ModeSwitchKey" ) );
  KConfigSkeleton::ItemString  *item_IMEngine_Pinyin_PageDownKey;
  item_IMEngine_Pinyin_PageDownKey = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/PageDownKey" ), m_IMEngine_Pinyin_PageDownKey, QString::fromLatin1( "period,equal,bracketright,Page_Down" ) );
  addItem( item_IMEngine_Pinyin_PageDownKey, QString::fromLatin1( "_IMEngine_Pinyin_PageDownKey" ) );
  KConfigSkeleton::ItemString  *item_IMEngine_Pinyin_PageUpKey;
  item_IMEngine_Pinyin_PageUpKey = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/PageUpKey" ), m_IMEngine_Pinyin_PageUpKey, QString::fromLatin1( "comma,minus,bracketleft,Page_Up" ) );
  addItem( item_IMEngine_Pinyin_PageUpKey, QString::fromLatin1( "_IMEngine_Pinyin_PageUpKey" ) );
  KConfigSkeleton::ItemInt  *item_IMEngine_Pinyin_SavePeriod;
  item_IMEngine_Pinyin_SavePeriod = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/SavePeriod" ), m_IMEngine_Pinyin_SavePeriod, 300 );
  addItem( item_IMEngine_Pinyin_SavePeriod, QString::fromLatin1( "_IMEngine_Pinyin_SavePeriod" ) );
  KConfigSkeleton::ItemBool  *item_IMEngine_Pinyin_ShowAllKeys;
  item_IMEngine_Pinyin_ShowAllKeys = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/ShowAllKeys" ), m_IMEngine_Pinyin_ShowAllKeys, false );
  addItem( item_IMEngine_Pinyin_ShowAllKeys, QString::fromLatin1( "_IMEngine_Pinyin_ShowAllKeys" ) );
  KConfigSkeleton::ItemInt  *item_IMEngine_Pinyin_SmartMatchLevel;
  item_IMEngine_Pinyin_SmartMatchLevel = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/SmartMatchLevel" ), m_IMEngine_Pinyin_SmartMatchLevel, 20 );
  addItem( item_IMEngine_Pinyin_SmartMatchLevel, QString::fromLatin1( "_IMEngine_Pinyin_SmartMatchLevel" ) );
  KConfigSkeleton::ItemBool  *item_IMEngine_Pinyin_Tone;
  item_IMEngine_Pinyin_Tone = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/Tone" ), m_IMEngine_Pinyin_Tone, false );
  addItem( item_IMEngine_Pinyin_Tone, QString::fromLatin1( "_IMEngine_Pinyin_Tone" ) );
  KConfigSkeleton::ItemBool  *item_IMEngine_Pinyin_User_DataBinary;
  item_IMEngine_Pinyin_User_DataBinary = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "/IMEngine/Pinyin/User/DataBinary" ), m_IMEngine_Pinyin_User_DataBinary, false );
  addItem( item_IMEngine_Pinyin_User_DataBinary, QString::fromLatin1( "_IMEngine_Pinyin_User_DataBinary" ) );
}

SmartPinyinConfig::~SmartPinyinConfig()
{
  if ( mSelf == this )
    staticSmartPinyinConfigDeleter.setObject( mSelf, 0, false );
}

